### ISSUE TITLE
Running mountebank via Docker

### ISSUE THREAD

**Issue by PetPython** [bbyars/mountebank#605]
#### Problem

When starting mountebank via Docker (see **docker-compose.yml** below) on custom port and trying to communicate with it via Postman, it doesn't seem to work even with the base GET-request:

![image](https://user-images.githubusercontent.com/42939994/112845010-09050d00-90ad-11eb-9412-a09b5cb61dab.png)

However, upon the start, the container log says it's up:
```
info: [mb:2525] mountebank v2.4.0 now taking orders - point your browser to http://localhost:2525/ for help
```
This is the exact message as when I start mountebank via terminal after npm installation. So where is the problem? If I call
```
sudo lsof -i:25025
```
, mountebank container definitely holds this very port. But REST-requests still do not work (terminal curls as well).

I face no problem working with npm-installed mountebank but I really need it to run in Docker.

#### Software versions used

```
OS                  : Ubuntu
mountebank          : 2.4.0
Installation method : docker-compose.yml
```

#### docker-compose.yml
```
version: '3'
services:
  mountebank:
    image: bbyars/mountebank:2.4.0
    container_name: mountebank
    network_mode: "bridge"
    ports:
      - '25025:25025'
```
Command to install and start:
```
docker-compose -f docker-compose.yml up -d
```
